(function(){
  function render(c){c.innerHTML=`<div class="card anim-fade"><div class="card-title"><span class="icon">📑</span>Citation Generator</div>
    <div class="form-row"><div class="form-group" style="flex:1;margin-bottom:0"><label>Author(s)</label><input type="text" id="ci-a" placeholder="Last, F.M."></div><div class="form-group" style="flex:1;margin-bottom:0"><label>Year</label><input type="text" id="ci-y" placeholder="2024"></div></div>
    <div class="form-group"><label>Title</label><input type="text" id="ci-t" placeholder="Title"></div>
    <div class="form-row"><div class="form-group" style="flex:1;margin-bottom:0"><label>Source</label><input type="text" id="ci-s" placeholder="Journal"></div><div class="form-group" style="flex:1;margin-bottom:0"><label>URL</label><input type="text" id="ci-u" placeholder="https://..."></div></div>
    <div class="form-row"><div class="form-group" style="margin-bottom:0"><label>Format</label><select id="ci-f"><option value="apa">APA 7th</option><option value="mla">MLA 9th</option><option value="ieee">IEEE</option><option value="chicago">Chicago</option></select></div><button class="btn btn-primary btn-sm" onclick="Cit.gen()" style="align-self:flex-end">Generate</button></div>
    <div id="ci-out" style="margin-top:16px;display:none"><div style="background:var(--bg-tertiary);border:1px solid var(--border);border-radius:8px;padding:14px;font-size:0.88rem" id="ci-res"></div><button class="btn btn-secondary btn-sm" style="margin-top:8px" onclick="navigator.clipboard.writeText(document.getElementById('ci-res').textContent);Toast.success('Copied!')">Copy</button></div></div>`;}
  window.Cit={gen(){const a=document.getElementById('ci-a').value.trim()||'Unknown',y=document.getElementById('ci-y').value.trim()||'n.d.',t=document.getElementById('ci-t').value.trim()||'Untitled',s=document.getElementById('ci-s').value.trim(),u=document.getElementById('ci-u').value.trim(),f=document.getElementById('ci-f').value;let c='';if(f==='apa')c=`${a} (${y}). ${t}${s?'. '+s:''}${u?'. '+u:''}`;else if(f==='mla')c=`${a}. "${t}."${s?' '+s+','} ${y}${u?', '+u:''}.`;else if(f==='ieee')c=`${a}, "${t},"${s?' '+s+','} ${y}${u?', '+u:''}.`;else c=`${a}. "${t}."${s?' '+s:''} (${y})${u?'. '+u:''}.`;document.getElementById('ci-res').textContent=c;document.getElementById('ci-out').style.display='';}};
  Router.registerRoute('#citation-gen','Citation Generator',render);
})();