(function(){
  function h2r(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)];}
  function r2s(r,g,b){r/=255;g/=255;b/=255;const mx=Math.max(r,g,b),mn=Math.min(r,g,b);let h,s,l=(mx+mn)/2;if(mx!==mn){const d=mx-mn;s=l>0.5?d/(2-mx-mn):d/(mx+mn);h=mx===r?((g-b)/d+(g<b?6:0))/6:mx===g?((b-r)/d+2)/6:((r-g)/d+4)/6;}else h=s=0;return[Math.round(h*360),Math.round(s*100),Math.round(l*100)];}
  function r2h(r,g,b){return'#'+[r,g,b].map(x=>x.toString(16).padStart(2,'0')).join('');}
  function render(c){c.innerHTML=`<div class="card anim-fade"><div class="card-title"><span class="icon">🎨</span>Color Picker</div>
    <div style="display:flex;gap:16px;flex-wrap:wrap"><div><input type="color" id="cp-col" value="#7b9aff" style="width:90px;height:90px;border:none;cursor:pointer;background:none" oninput="CP.upd()"><div class="color-preview" id="cp-prev" style="background:#7b9aff"></div></div>
    <div style="flex:1;min-width:160px"><div class="form-group"><label>HEX</label><input type="text" id="cp-hex" value="#7b9aff" oninput="CP.fh()"></div><div class="form-group"><label>RGB</label><input type="text" id="cp-rgb" readonly></div><div class="form-group"><label>HSL</label><input type="text" id="cp-hsl" readonly></div><div style="display:flex;gap:8px"><button class="btn btn-secondary btn-sm" onclick="CP.cp('hex')">Copy HEX</button><button class="btn btn-secondary btn-sm" onclick="CP.cp('rgb')">Copy RGB</button></div></div></div>
    <div style="margin-top:12px"><label style="font-size:0.78rem;color:var(--text-secondary)">Palette</label><div id="cp-pal" style="display:flex;gap:4px;flex-wrap:wrap;margin-top:4px"></div></div></div>`;CP.upd();}
  window.CP={upd(){const hex=document.getElementById('cp-col').value,[r,g,b]=h2r(hex),[h,s,l]=r2s(r,g,b);document.getElementById('cp-hex').value=hex;document.getElementById('cp-rgb').value=`rgb(${r},${g},${b})`;document.getElementById('cp-hsl').value=`hsl(${h},${s}%,${l}%)`;document.getElementById('cp-prev').style.background=hex;this.gp(hex);},fh(){let h=document.getElementById('cp-hex').value.trim();if(!h.startsWith('#'))h='#'+h;if(/^#[0-9a-fA-F]{6}$/.test(h)){document.getElementById('cp-col').value=h;this.upd();}},cp(t){navigator.clipboard.writeText(document.getElementById(t==='hex'?'cp-hex':'cp-rgb').value).then(()=>Toast.success('Copied!'));},gp(hex){const[r,g,b]=h2r(hex);let pal='';for(let i=-2;i<=2;i++){const f=1+i*0.2;pal+=`<div style="width:32px;height:32px;border-radius:6px;background:${r2h(Math.min(255,Math.max(0,r*f)),Math.min(255,Math.max(0,g*f)),Math.min(255,Math.max(0,b*f)))};cursor:pointer;border:1px solid var(--border)" onclick="document.getElementById('cp-col').value=this.style.backgroundColor;CP.upd()"></div>`;}document.getElementById('cp-pal').innerHTML=pal;}};
  Router.registerRoute('#color-picker','Color Picker',render);
})();